import './globals.css';
import { Jost } from 'next/font/google';
import Header from '@/components/Header/Header';
import { SiteProvider } from '@/context/SiteContext';

import dynamic from 'next/dynamic';

const DynamicFooter = dynamic(() => import('@/components/Footer/Footer'));

const jost = Jost({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk-UA">
      <body className={jost.className}>
        <SiteProvider>
          <Header />
          <main>{children}</main>
          <DynamicFooter />
        </SiteProvider>
      </body>
    </html>
  );
}
